version: '3'

services:
  psql-container:
    image: postgres:latest
    container_name: psql-container
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_MULTIPLE_DATABASES:  authentication_db,order_service_db,inventory_service_db,delivery_service_db,payment_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./databases_init:/docker-entrypoint-initdb.d

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure
