spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: "https://localhost/api"
          predicates:
            - Path=/**


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/