server:
  port: 8761


spring:
  application:
    name: discovery
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ./discovery/config


eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/